# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Enable Corne OLED Display & Pointing
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_POINTING=y

# Enable WPM status
CONFIG_ZMK_WPM_STATUS=y
